token: isystem_token
subscribe:
  iconfig_pub: tcp://127.0.0.1:65401
scripts:
  timezone: '/apps/etc/init.d/S72timezone'
  lighttpd: '/apps/etc/init.d/S81lighttpd restart'
  network:  '/apps/etc/init.d/S80network restart'
delayed_work:
  network: 2000
system_led:
  interval: 1
  address: '0x201C0020'
  on: '0x08'
  off: '0x00'
